-- =============================================================================
-- 06_audit_table.sql
-- Creates the pipeline run audit table written to by snowflake_state_manager.py
--
-- This table serves two purposes simultaneously:
--   1. State tracking — the Lambda queries MAX(run_date) WHERE status = 'SUCCESS'
--      to determine the incremental start_date for the next run
--   2. Operations log — every run is recorded with its record count, S3 keys,
--      timing, and error message if it failed, giving full pipeline observability
--
-- One row is written per entity per Lambda invocation:
--   - entity = 'employees'    after the employee stage completes
--   - entity = 'terminations' after the termination stage completes
--   - entity = 'pipeline'     only on failure, to record the error
-- =============================================================================

USE DATABASE PIPELINE_AUDIT;
USE SCHEMA   PIPELINE_AUDIT.INGESTION;


CREATE TABLE IF NOT EXISTS PIPELINE_AUDIT.INGESTION.RUNS (

    RUN_ID          VARCHAR         NOT NULL    COMMENT 'UUID generated by the Lambda for each entity run',
    RUN_DATE        DATE            NOT NULL    COMMENT 'Calendar date the Lambda executed',
    ENTITY          VARCHAR         NOT NULL    COMMENT 'employees | terminations | pipeline',
    RECORDS_STAGED  INTEGER         NOT NULL    COMMENT 'Number of records written to S3 in this run',
    S3_KEY          VARCHAR                     COMMENT 'JSON array of S3 keys staged — one key per page',
    STATUS          VARCHAR         NOT NULL    COMMENT 'SUCCESS | FAILED',
    STARTED_AT      TIMESTAMP_TZ    NOT NULL    COMMENT 'UTC timestamp the entity extraction began',
    COMPLETED_AT    TIMESTAMP_TZ                COMMENT 'UTC timestamp the audit record was written',
    ERROR_MESSAGE   VARCHAR                     COMMENT 'Exception message if STATUS = FAILED, else NULL',

    PRIMARY KEY (RUN_ID)
)
COMMENT = 'Pipeline run history written by the Workday Lambda ingestion pipeline. Used for incremental state tracking and operational monitoring.';


-- -----------------------------------------------------------------------------
-- Indexes (Snowflake uses search optimization, not traditional indexes)
-- Enable search optimization on the columns most frequently filtered
-- -----------------------------------------------------------------------------

-- Allows fast MAX(run_date) queries by the Lambda state manager
ALTER TABLE PIPELINE_AUDIT.INGESTION.RUNS
    ADD SEARCH OPTIMIZATION ON EQUALITY(ENTITY, STATUS);


-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------

-- Lambda service user needs INSERT + SELECT (reads state, writes records)
GRANT INSERT, SELECT ON PIPELINE_AUDIT.INGESTION.RUNS TO ROLE PIPELINE_ROLE;

-- Analysts can monitor pipeline health but cannot modify audit records
GRANT SELECT ON PIPELINE_AUDIT.INGESTION.RUNS TO ROLE ANALYST_ROLE;


-- =============================================================================
-- OPERATIONAL QUERIES
-- =============================================================================

-- Last successful run per entity
SELECT
    ENTITY,
    MAX(RUN_DATE)     AS LAST_SUCCESS_DATE,
    MAX(COMPLETED_AT) AS LAST_SUCCESS_AT
FROM PIPELINE_AUDIT.INGESTION.RUNS
WHERE STATUS = 'SUCCESS'
GROUP BY ENTITY
ORDER BY ENTITY;


-- Full run history for the last 30 days
SELECT
    RUN_DATE,
    ENTITY,
    STATUS,
    RECORDS_STAGED,
    STARTED_AT,
    COMPLETED_AT,
    DATEDIFF('second', STARTED_AT, COMPLETED_AT) AS DURATION_SECONDS,
    ERROR_MESSAGE
FROM PIPELINE_AUDIT.INGESTION.RUNS
WHERE RUN_DATE >= DATEADD('day', -30, CURRENT_DATE())
ORDER BY STARTED_AT DESC;


-- Failed runs in the last 7 days
SELECT
    RUN_DATE,
    ENTITY,
    ERROR_MESSAGE,
    STARTED_AT
FROM PIPELINE_AUDIT.INGESTION.RUNS
WHERE STATUS     = 'FAILED'
  AND RUN_DATE  >= DATEADD('day', -7, CURRENT_DATE())
ORDER BY STARTED_AT DESC;


-- Daily record volume trend for terminations
SELECT
    RUN_DATE,
    SUM(RECORDS_STAGED) AS TERMINATIONS_STAGED
FROM PIPELINE_AUDIT.INGESTION.RUNS
WHERE ENTITY = 'terminations'
  AND STATUS = 'SUCCESS'
GROUP BY RUN_DATE
ORDER BY RUN_DATE DESC;
