"""
fake_data.py
Seed data for the Mock Workday API.
Realistic employee and termination records for pipeline development/testing.
"""

EMPLOYEES = [
    {
        "employee_id": "EMP-1001",
        "first_name": "Jordan",
        "last_name": "Mitchell",
        "email": "jordan.mitchell@equipmentshare.com",
        "job_title": "Equipment Technician",
        "department": "Field Operations",
        "location_city": "Columbia",
        "location_state": "MO",
        "location_country": "USA",
        "hire_date": "2020-03-15",
        "employment_status": "Active",
        "worker_type": "Employee",
        "manager_id": "EMP-0201",
    },
    {
        "employee_id": "EMP-1002",
        "first_name": "Priya",
        "last_name": "Sharma",
        "email": "priya.sharma@equipmentshare.com",
        "job_title": "Data Analyst",
        "department": "HR Analytics",
        "location_city": "Kansas City",
        "location_state": "MO",
        "location_country": "USA",
        "hire_date": "2021-07-01",
        "employment_status": "Active",
        "worker_type": "Employee",
        "manager_id": "EMP-0105",
    },
    {
        "employee_id": "EMP-1003",
        "first_name": "Marcus",
        "last_name": "Evans",
        "email": "marcus.evans@equipmentshare.com",
        "job_title": "Branch Manager",
        "department": "Operations",
        "location_city": "Dallas",
        "location_state": "TX",
        "location_country": "USA",
        "hire_date": "2018-11-20",
        "employment_status": "Terminated",
        "worker_type": "Employee",
        "manager_id": "EMP-0088",
    },
    {
        "employee_id": "EMP-1004",
        "first_name": "Samantha",
        "last_name": "Lee",
        "email": "samantha.lee@equipmentshare.com",
        "job_title": "HR Business Partner",
        "department": "Human Resources",
        "location_city": "Denver",
        "location_state": "CO",
        "location_country": "USA",
        "hire_date": "2022-01-10",
        "employment_status": "Active",
        "worker_type": "Employee",
        "manager_id": "EMP-0044",
    },
    {
        "employee_id": "EMP-1005",
        "first_name": "Derek",
        "last_name": "Nguyen",
        "email": "derek.nguyen@equipmentshare.com",
        "job_title": "Fleet Coordinator",
        "department": "Field Operations",
        "location_city": "Atlanta",
        "location_state": "GA",
        "location_country": "USA",
        "hire_date": "2019-05-06",
        "employment_status": "Terminated",
        "worker_type": "Employee",
        "manager_id": "EMP-0201",
    },
    {
        "employee_id": "EMP-1006",
        "first_name": "Chloe",
        "last_name": "Watson",
        "email": "chloe.watson@equipmentshare.com",
        "job_title": "Software Engineer",
        "department": "Technology",
        "location_city": "Austin",
        "location_state": "TX",
        "location_country": "USA",
        "hire_date": "2023-03-27",
        "employment_status": "Active",
        "worker_type": "Employee",
        "manager_id": "EMP-0312",
    },
    {
        "employee_id": "EMP-1007",
        "first_name": "Tariq",
        "last_name": "Okafor",
        "email": "tariq.okafor@equipmentshare.com",
        "job_title": "Safety Coordinator",
        "department": "EHS",
        "location_city": "Houston",
        "location_state": "TX",
        "location_country": "USA",
        "hire_date": "2017-08-14",
        "employment_status": "Terminated",
        "worker_type": "Employee",
        "manager_id": "EMP-0088",
    },
    {
        "employee_id": "EMP-1008",
        "first_name": "Amanda",
        "last_name": "Torres",
        "email": "amanda.torres@equipmentshare.com",
        "job_title": "Recruiter",
        "department": "Human Resources",
        "location_city": "Phoenix",
        "location_state": "AZ",
        "location_country": "USA",
        "hire_date": "2024-01-08",
        "employment_status": "Active",
        "worker_type": "Employee",
        "manager_id": "EMP-0044",
    },
]


TERMINATIONS = [
    {
        "termination_id": "TERM-3001",
        "employee_id": "EMP-1003",
        "termination_date": "2024-06-30",
        "last_day_of_work": "2024-06-28",
        "termination_type": "Voluntary",
        "termination_reason": "Resignation",
        "termination_reason_detail": "Accepted external offer — competitor company",
        "rehire_eligible": True,
        "recorded_by": "HR-samantha.lee",
        "recorded_at": "2024-07-01T09:15:00Z",
    },
    {
        "termination_id": "TERM-3002",
        "employee_id": "EMP-1005",
        "termination_date": "2024-09-15",
        "last_day_of_work": "2024-09-15",
        "termination_type": "Involuntary",
        "termination_reason": "Performance",
        "termination_reason_detail": "Failed to meet KPIs for three consecutive quarters",
        "rehire_eligible": False,
        "recorded_by": "HR-samantha.lee",
        "recorded_at": "2024-09-16T10:00:00Z",
    },
    {
        "termination_id": "TERM-3003",
        "employee_id": "EMP-1007",
        "termination_date": "2025-01-10",
        "last_day_of_work": "2025-01-10",
        "termination_type": "Voluntary",
        "termination_reason": "Retirement",
        "termination_reason_detail": "Employee reached retirement age and elected to retire",
        "rehire_eligible": True,
        "recorded_by": "HR-amanda.torres",
        "recorded_at": "2025-01-11T08:30:00Z",
    },
    {
        "termination_id": "TERM-3004",
        "employee_id": "EMP-2010",
        "termination_date": "2024-03-01",
        "last_day_of_work": "2024-02-29",
        "termination_type": "Involuntary",
        "termination_reason": "Layoff",
        "termination_reason_detail": "Position eliminated as part of Q1 2024 RIF",
        "rehire_eligible": True,
        "recorded_by": "HR-samantha.lee",
        "recorded_at": "2024-03-01T14:00:00Z",
    },
    {
        "termination_id": "TERM-3005",
        "employee_id": "EMP-2045",
        "termination_date": "2024-11-22",
        "last_day_of_work": "2024-11-22",
        "termination_type": "Voluntary",
        "termination_reason": "Resignation",
        "termination_reason_detail": "Relocating out of state for personal reasons",
        "rehire_eligible": True,
        "recorded_by": "HR-amanda.torres",
        "recorded_at": "2024-11-23T09:45:00Z",
    },
    {
        "termination_id": "TERM-3006",
        "employee_id": "EMP-2067",
        "termination_date": "2025-02-14",
        "last_day_of_work": "2025-02-14",
        "termination_type": "Involuntary",
        "termination_reason": "Termination for Cause",
        "termination_reason_detail": "Violation of company code of conduct",
        "rehire_eligible": False,
        "recorded_by": "HR-samantha.lee",
        "recorded_at": "2025-02-14T16:00:00Z",
    },
    {
        "termination_id": "TERM-3007",
        "employee_id": "EMP-2089",
        "termination_date": "2024-07-19",
        "last_day_of_work": "2024-07-19",
        "termination_type": "Voluntary",
        "termination_reason": "Resignation",
        "termination_reason_detail": "Pursuing graduate education full-time",
        "rehire_eligible": True,
        "recorded_by": "HR-amanda.torres",
        "recorded_at": "2024-07-20T11:00:00Z",
    },
    {
        "termination_id": "TERM-3008",
        "employee_id": "EMP-2101",
        "termination_date": "2024-12-31",
        "last_day_of_work": "2024-12-31",
        "termination_type": "Voluntary",
        "termination_reason": "Resignation",
        "termination_reason_detail": "Better compensation package elsewhere",
        "rehire_eligible": True,
        "recorded_by": "HR-amanda.torres",
        "recorded_at": "2025-01-02T08:00:00Z",
    },
]
